name: Deploy gfnetdiag2-460b05
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-code-agent.yml
    with:
      agent-manifest: agents/gfnetdiag2-460b05/agent.yaml
      build-context: agents/autopilot-agent/simple-autopilot-agent
      build-method: python
      entry-file: main.py
