name: Deploy autopilot-agent
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/_deploy-code-agent.yml
    with:
      agent-manifest: agents/autopilot-agent/agent.yaml
      build-context: agents/autopilot-agent/simple-autopilot-agent
      build-method: python
      entry-file: main.py
